### ISSUE TITLE
Strange applyNext behavior 

### ISSUE THREAD

**Issue by sbmaxx** [bem/bem-xjst#121]
I think this is about wrong `b-page.bemhtml.js` template from islands — http://pastebin.com/JFVfYR1D

Paste it into http://bem.github.io/bem-xjst/ and use this bemjson:
```js
([{
    block: 'b-page'
},{
    block: 'b-page'
},{
    block: 'b-page'
},{
    block: 'b-page'
},{
    block: 'b-page'
},{
    block: 'b-page'
}]);
```

You will get:

```html
<body class="b-page b-page__body i-ua i-ua i-bem" data-bem='{"i-ua":{}}'></body>
<body class="b-page b-page__body i-ua i-ua i-ua i-bem" data-bem='{"i-ua":{}}'></body>
<body class="b-page b-page__body i-ua i-ua i-ua i-ua i-bem" data-bem='{"i-ua":{}}'></body>
<body class="b-page b-page__body i-ua i-ua i-ua i-ua i-ua i-bem" data-bem='{"i-ua":{}}'></body>
<body class="b-page b-page__body i-ua i-ua i-ua i-ua i-ua i-ua i-bem" data-bem='{"i-ua":{}}'></body>
```

It can be easily repaired by merging `mix mode` in template to http://pastebin.com/2nY1Z1tm

**Comment by sbmaxx** [comment]
@veged @indutny

**Comment by veged** [comment]
looks like `applyNext()` returns `mix` previously modified through `push` :-/

**Comment by tadatuta** [comment]
That's what we decided to be not a bug of `bem-xjst` in https://github.com/bem/bem-xjst/issues/92 so it should be fixed in templates.

**Comment by veged** [comment]
@tadatuta looks similar, but I think it's not the same because there is no another template for `mix` with static literally defined array

**Comment by zxqfox** [comment]
@veged After reading sources I don't see it's another bug:
```js
  mix()([{elem: 'body'}]),
  // ...
  mix()(function () {
    var mix = applyNext() || [], ...;
    mix.push({block: 'i-ua'});
    // etc... 
```

Still the same reference to static array. https://nda.ya.ru/3R7paQ

**Comment by veged** [comment]
hm... maybe it was already fixed when I look at `islands` code

**Comment by zxqfox** [comment]
@veged Yeah, sorry. Here the link: https://nda.ya.ru/3R8AaW

**Comment by arikon** [comment]
Considered as won't fix because of error in templates.
